<?php
return [
    'stops' => [
        [
            'day_id' => 1,
            'location' => 'Camp Nou',
            'type' => 'Stadium',
            'address' => 'Les Corts, 08028 Barcelona, Spain',
            'visited' => true,
            'rating' => 4,
            'notes' => 'It was a nice experience, we even visited the museum with all the trophies FC Barcelona won',
        ],
        [
            'day_id' => 1,
            'location' => 'La Rambla',
            'type' => 'Street',
            'address' => 'La Rambla, Barcelona, Spain',
            'visited' => true,
            'rating' => 5,
            'notes' => 'A bustling street with lots of shops and restaurants',
        ],
        [
            'day_id' => 2,
            'location' => 'Sagrada Família',
            'type' => 'Church',
            'address' => 'Carrer de Mallorca, 401, 08013 Barcelona, Spain',
            'visited' => true,
            'rating' => 5,
            'notes' => 'Stunning architecture, a must-see in Barcelona',
        ],
        [
            'day_id' => 2,
            'location' => 'Park Güell',
            'type' => 'Park',
            'address' => 'Carrer d\'Olot, 5, 08024 Barcelona, Spain',
            'visited' => true,
            'rating' => 4,
            'notes' => 'Beautiful park designed by Gaudí with great views',
        ],
        [
            'day_id' => 3,
            'location' => 'Picasso Museum',
            'type' => 'Museum',
            'address' => 'Carrer Montcada, 15-23, 08003 Barcelona, Spain',
            'visited' => true,
            'rating' => 4,
            'notes' => 'Interesting collection of Picasso’s early works',
        ],
        [
            'day_id' => 3,
            'location' => 'Gothic Quarter',
            'type' => 'Neighborhood',
            'address' => 'Barcelona, Spain',
            'visited' => true,
            'rating' => 5,
            'notes' => 'Charming old streets with historic buildings',
        ],
        [
            'day_id' => 4,
            'location' => 'La Boqueria Market',
            'type' => 'Market',
            'address' => 'La Rambla, 91, 08001 Barcelona, Spain',
            'visited' => true,
            'rating' => 5,
            'notes' => 'A vibrant market with a variety of fresh produce and local delicacies',
        ],
        [
            'day_id' => 4,
            'location' => 'Casa Batlló',
            'type' => 'Building',
            'address' => 'Passeig de Gràcia, 43, 08007 Barcelona, Spain',
            'visited' => true,
            'rating' => 5,
            'notes' => 'Another Gaudí masterpiece, known for its unique design',
        ],
        [
            'day_id' => 5,
            'location' => 'Montjuïc Castle',
            'type' => 'Castle',
            'address' => 'Ctra. de Montjuïc, 66, 08038 Barcelona, Spain',
            'visited' => true,
            'rating' => 4,
            'notes' => 'Historical castle with panoramic views of the city',
        ],
        [
            'day_id' => 5,
            'location' => 'Magic Fountain',
            'type' => 'Fountain',
            'address' => 'Plaça de Carles Buïgas, 1, 08038 Barcelona, Spain',
            'visited' => true,
            'rating' => 5,
            'notes' => 'Spectacular water and light show in the evenings',
        ],
        [
            'day_id' => 6,
            'location' => 'Barri Gòtic',
            'type' => 'Neighborhood',
            'address' => 'Barcelona, Spain',
            'visited' => true,
            'rating' => 4,
            'notes' => 'Historic center of Barcelona with medieval architecture',
        ],
        [
            'day_id' => 6,
            'location' => 'El Born',
            'type' => 'Neighborhood',
            'address' => 'Barcelona, Spain',
            'visited' => true,
            'rating' => 5,
            'notes' => 'Trendy area with a vibrant nightlife and art scene',
        ],
        [
            'day_id' => 7,
            'location' => 'Tibidabo',
            'type' => 'Amusement Park',
            'address' => 'Carrer del Tibidabo, 3-4, 08035 Barcelona, Spain',
            'visited' => true,
            'rating' => 4,
            'notes' => 'Amusement park with stunning views of Barcelona',
        ],
        [
            'day_id' => 7,
            'location' => 'Gran Teatre del Liceu',
            'type' => 'Theatre',
            'address' => 'La Rambla, 51-59, 08002 Barcelona, Spain',
            'visited' => true,
            'rating' => 5,
            'notes' => 'Historic opera house with beautiful architecture',
        ],
        [
            'day_id' => 8,
            'location' => 'Palau de la Música Catalana',
            'type' => 'Concert Hall',
            'address' => 'Carrer del Palau de la Música, 4-6, 08003 Barcelona, Spain',
            'visited' => true,
            'rating' => 5,
            'notes' => 'Stunning concert hall known for its modernist design',
        ],
        [
            'day_id' => 8,
            'location' => 'Raval',
            'type' => 'Neighborhood',
            'address' => 'Barcelona, Spain',
            'visited' => true,
            'rating' => 4,
            'notes' => 'Diverse neighborhood with interesting shops and restaurants',
        ],
        [
            'day_id' => 9,
            'location' => 'Passeig de Gràcia',
            'type' => 'Street',
            'address' => 'Barcelona, Spain',
            'visited' => true,
            'rating' => 4,
            'notes' => 'Elegant street with high-end shops and architecture',
        ],
        [
            'day_id' => 9,
            'location' => 'Casa Milà',
            'type' => 'Building',
            'address' => 'Passeig de Gràcia, 92, 08008 Barcelona, Spain',
            'visited' => true,
            'rating' => 5,
            'notes' => 'Gaudí’s iconic building also known as La Pedrera',
        ],
        [
            'day_id' => 10,
            'location' => 'Hospital de Sant Pau',
            'type' => 'Hospital',
            'address' => 'Carrer de Sant Antoni Maria Claret, 167, 08025 Barcelona, Spain',
            'visited' => true,
            'rating' => 4,
            'notes' => 'A beautiful modernist building and former hospital',
        ],
        [
            'day_id' => 10,
            'location' => 'Museu Nacional d\'Art de Catalunya',
            'type' => 'Museum',
            'address' => 'Palau Nacional, Parc de Montjuïc, s/n, 08038 Barcelona, Spain',
            'visited' => true,
            'rating' => 5,
            'notes' => 'Museum with a vast collection of Catalan art',
        ],
        [
            'day_id' => 11,
            'location' => 'Barcelona Zoo',
            'type' => 'Zoo',
            'address' => 'Parc de la Ciutadella, 08003 Barcelona, Spain',
            'visited' => true,
            'rating' => 4,
            'notes' => 'Zoo with a variety of animals and beautiful park',
        ],
        [
            'day_id' => 11,
            'location' => 'Parc de la Ciutadella',
            'type' => 'Park',
            'address' => 'Carrer de la Ronda de Sant Pere, 08003 Barcelona, Spain',
            'visited' => true,
            'rating' => 5,
            'notes' => 'Lovely park with a lake, perfect for relaxing',
        ],
        [
            'day_id' => 12,
            'location' => 'Barceloneta Beach',
            'type' => 'Beach',
            'address' => 'Barcelona, Spain',
            'visited' => true,
            'rating' => 5,
            'notes' => 'Popular beach with plenty of restaurants and bars nearby',
        ],
        [
            'day_id' => 12,
            'location' => 'Avenida Diagonal',
            'type' => 'Street',
            'address' => 'Barcelona, Spain',
            'visited' => true,
            'rating' => 4,
            'notes' => 'Wide avenue with high-end shops and interesting architecture',
        ],
        [
            'day_id' => 13,
            'location' => 'Museu d\'Historia de Barcelona',
            'type' => 'Museum',
            'address' => 'Plaça del Rei, 08002 Barcelona, Spain',
            'visited' => true,
            'rating' => 4,
            'notes' => 'Museum showcasing the history of Barcelona',
        ],
        [
            'day_id' => 13,
            'location' => 'Liceu Opera House',
            'type' => 'Theatre',
            'address' => 'La Rambla, 51-59, 08002 Barcelona, Spain',
            'visited' => true,
            'rating' => 5,
            'notes' => 'Famous opera house with an elegant interior',
        ],
        [
            'day_id' => 14,
            'location' => 'Arc de Triomf',
            'type' => 'Monument',
            'address' => 'Passeig de Lluís Companys, 08003 Barcelona, Spain',
            'visited' => true,
            'rating' => 4,
            'notes' => 'Triumphal arch and a popular photo spot',
        ],
        [
            'day_id' => 14,
            'location' => 'Torre Glòries',
            'type' => 'Skyscraper',
            'address' => 'Avinguda Diagonal, 211, 08018 Barcelona, Spain',
            'visited' => true,
            'rating' => 5,
            'notes' => 'Modern skyscraper with an impressive design',
        ],
    ]
];
